version: '3.7'

volumes:
    trarepo-development-db-data:
networks:
    trarepo-development-network:

services:
    development-db:
        build:
            context: ./db
        ports:
            - '5432:5432'
        tty: true
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - trarepo-development-db-data:/var/lib/postgresql/data
        networks:
            - trarepo-development-network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: trarepo106090
            POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

    development-api:
        build:
            context: .
            target: development
        ports:
            - '3000:3000'
        tty: true
        command: sh -c "npm run start:dev"
        volumes:
            - .:/trarepo-api
            - /trarepo-api/node_modules
        networks:
            - trarepo-development-network
