name: Trarepo API Test CI

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build Container
              run: docker-compose -f docker-compose.test.yml build
            - name: Execute Test
              run: docker-compose -f docker-compose.test.yml up